'use strict';

let items = [
  { id:  1, line1: 'Молоко 3.2%',        line2: '2 пакета, магазин у дома', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  2, line1: 'Хлеб ржаной',        line2: '', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 26, line1: 'Бородинский',        line2: '400 г', parentId: 2, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 27, line1: 'Столичный',          line2: '500 г', parentId: 2, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  3, line1: 'Яблоки',            line2: 'Голден, ~1.5 кг', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 28, line1: 'Голден',             line2: '500 г', parentId: 3, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 29, line1: 'Гренни Смит',        line2: '400 г', parentId: 3, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 30, line1: 'Фуджи',             line2: '300 г', parentId: 3, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 31, line1: 'Симиренко',          line2: '300 г', parentId: 3, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  4, line1: 'Кофе',              line2: 'Арабика, зерно, 250 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  5, line1: 'Зубная паста',      line2: '', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  6, line1: 'Шампунь',           line2: 'Для нормальных волос', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  7, line1: 'Стиральный порошок', line2: 'Автомат, 3 кг', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  8, line1: 'Батарейки AA',      line2: '4 штуки', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id:  9, line1: 'Сыр Гауда',         line2: '200 г, нарезка', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 10, line1: 'Яйца',              line2: '10 штук, C1', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 11, line1: 'Масло сливочное',   line2: '82.5%, 200 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 12, line1: 'Греческий йогурт',  line2: '0%, 500 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 13, line1: 'Помидоры',          line2: '1 кг, черри', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 14, line1: 'Огурцы',            line2: '500 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 15, line1: 'Куриное филе',      line2: '1 кг, охлаждённое', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 16, line1: 'Макароны',          line2: 'Спагетти, 400 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 17, line1: 'Томатная паста',    line2: '2 банки по 140 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 18, line1: 'Оливковое масло',   line2: 'Extra Virgin, 500 мл', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 19, line1: 'Чай зелёный',       line2: '25 пакетиков', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 20, line1: 'Бананы',            line2: '1 кг', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 21, line1: 'Апельсины',         line2: '1.5 кг', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 22, line1: 'Туалетная бумага',  line2: '12 рулонов', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 23, line1: 'Мыло жидкое',       line2: 'Антибактериальное, 500 мл', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 24, line1: 'Сахар',             line2: '1 кг, белый', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
  { id: 25, line1: 'Соль',              line2: 'Морская, мелкая, 500 г', parentId: null, status: 'open', tags: [], createdAt: Date.now(), updatedAt: Date.now() },
];

let nextId = 32;
